services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/agile-calculator
    command: jupyter lab --notebook-dir /agile-calculator/notebooks --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    env_file:
     - .env
