description = "仕様の策定"

prompt = """
入力されたユーザーストーリーをもとに、具体的な仕様を定義してください。
ユーザーストーリー: {{args}}

ユーザーストーリーを適切な粒度に分割して、以下のフォーマットで具体的な仕様を定義してください。

# 仕様1. ユーザーストーリーのタイトル

- 仕様の説明
- 受け入れ条件

# 仕様2. ユーザーストーリーのタイトル

- 仕様の説明
- 受け入れ条件

# 仕様3. ユーザーストーリーのタイトル

- 仕様の説明
- 受け入れ条件
"""
