description = "仕様の策定"

prompt = """
入力: {{args}}（ユーザーストーリー）

出力（Markdown のみ）:
## 概要
- ユーザーストーリーの要点（1〜2行）

## 分割されたサブストーリー
- サブストーリー1: タイトル — 1行の説明（誰が何を何のために）
- サブストーリー2: タイトル — 1行の説明
（必要に応じて「（優先: 高 / 見積: 3h）」のように追記）

## 主要な受け入れ条件（サブストーリーごと）
- サブストーリー1:
  - 受け入れ条件A（短文）
  - 受け入れ条件B
- サブストーリー2:
  - 受け入れ条件A

## 確認事項（ユーザーへ投げる質問、必要なら1〜2件）
- 例: データはCSVで提供されますか？
"""
