description = "タスクに分割する"

prompt = """
入力: {{args}}（`plan` の Markdown 出力を引用可）

出力（Markdown のみ）:
## 概要
- 優先度と合計見積（1行）

## チケット（実装タスク）
- タスク1: タイトル — 目的（1行）
  - 変更/追加ファイルの候補: `path/to/file.py`
  - 実装手順（3〜5ステップ、短文）
  - 見積: 3h
  - テスト: pytest の想定テスト名（短文）
- タスク2: ...

## 完了条件（チェックリスト）
- [ ] 単体テストが通る
- [ ] ruff/ty のチェッククリア
- [ ] README に追記
"""
