name: Create PR with Gemini

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'The issue number to associate with the PR'
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - uses: mxschmitt/action-tmate@v3
      - name: Fetch Issue Details
        run: |
          GH_ISSUE=`gh issue view ${{ github.event.inputs.issue_number }} --json number,title,url`
          echo "GH_ISSUE=$GH_ISSUE" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Increments with Gemini CLI
        run: |
          GH_ISSUE_NUMBER=$(echo $GH_ISSUE | jq -r '.number')
          GH_ISSUE_TITLE=$(echo $GH_ISSUE | jq -r '.title')
          git config --global user.name KentFujii
          git config --global user.email kent.where.the.light.is@gmail.com
          git config --global push.default current
          npm install -g @google/gemini-cli
          gemini -y -p "ghコマンドでissue ${GH_ISSUE_NUMBER}を読み込み、ワーキングアグリーメントに従ってプログラミングしてください。"
          # NOTE: 以下の処理をgeminiに移行
          git checkout -b "gemini/github-run-id-${GITHUB_RUN_ID}"
          git add .
          git commit -m "${GH_ISSUE_TITLE}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Create the Pull Request
        run: |
          GH_ISSUE_TITLE=$(echo $GH_ISSUE | jq -r '.title')
          GH_ISSUE_URL=$(echo $GH_ISSUE | jq -r '.url')
          gh pr create --title "$GH_ISSUE_TITLE" --body "$GH_ISSUE_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
