name: Create PR with Gemini

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'The issue number to associate with the PR'
        required: true
        default: 'gemini/fix-typos'
      commit_message:
        description: 'The commit message'
        required: true
        default: 'docs: Fix typos in README.md'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - uses: mxschmitt/action-tmate@v3
      - name: Install Gemini CLI
        run: |
          npm install -g @google/gemini-cli
          gemini -s -y -p "このリポジトリの解説をしてください"
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
          