name: Create PR with Gemini

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'The issue number to associate with the PR'
        required: true
        default: 'gemini/fix-typos'
      commit_message:
        description: 'The commit message'
        required: true
        default: 'docs: Fix typos in README.md'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - uses: mxschmitt/action-tmate@v3
      - name: Fetch Issue Details
        run: |
          GH_ISSUE=`gh issue view ${{ github.event.inputs.issue_number }} --json title,body`
          GH_ISSUE_TITLE=$(echo $GH_ISSUE | jq -r '.title')
          GH_ISSUE_BODY=$(echo $GH_ISSUE | jq -r '.body')
          echo "GH_ISSUE_TITLE=$GH_ISSUE_TITLE" >> $GITHUB_ENV
          echo "GH_ISSUE_BODY=$GH_ISSUE_BODY" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Diffs with Gemini CLI
        run: |
          npm install -g @google/gemini-cli
          gemini -y -p "$GH_ISSUE_BODY"
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Print environment variables
        run: |
          echo $GH_ISSUE_TITLE
          echo $GH_ISSUE_BODY
