name: Create PR with Gemini

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'The issue number to associate with the PR'
        required: true
        default: 'gemini/fix-typos'
      commit_message:
        description: 'The commit message'
        required: true
        default: 'docs: Fix typos in README.md'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - uses: mxschmitt/action-tmate@v3
      - name: execute Gemini CLI with GH CLI
        run: |
          npm install -g @google/gemini-cli
          GH_ISSUE=`gh issue view ${{ github.event.inputs.issue_number }} --json title,body`
          GH_ISSUE_TITLE=$(echo $GH_ISSUE | jq -r '.title')
          GH_ISSUE_BODY=$(echo $GH_ISSUE | jq -r '.body')
          echo "Issue Title: $GH_ISSUE_TITLE"
          echo "Issue Body: $GH_ISSUE_BODY"
          gemini -s -y -p "$GH_ISSUE_BODY"
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: execute gh cli
      #   run: |
      #     gh issue view ${{ github.event.inputs.issue_number }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
          