name: Run from comment

on:
  issue_comment:
    types: [created]

jobs:
  run-from-comment:
    if: startsWith(github.event.comment.body, '/agile-calculator')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get command
        id: get-command
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          COMMAND=$(echo "$COMMENT_BODY" | sed 's/\/agile-calculator //')
          echo "COMMAND=$COMMAND" >> $GITHUB_ENV

      - name: Run agile-calculator
        id: run-agile-calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_SERVER_URL: ${{ secrets.JIRA_SERVER_URL }}
        run: |
          docker compose build
          OUTPUT=$(docker compose run --rm jupyter agile-calculator $COMMAND)
          echo "OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh pr comment $PR_NUMBER --body "
          \`\`\`
          ${{ env.OUTPUT }}
          \`\`\`
          "
